# Generated by Django 3.1.7 on 2021-03-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0002_auto_20210228_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='dirección',
            field=models.CharField(max_length=50, verbose_name='La dirección'),
        ),
    ]
